apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  namespace: default
spec:
  replicas: 2
  #serviceName: eureka
  selector:
    matchLabels:
      k8s-app: eureka
  template:
    metadata:
      labels:
        k8s-app: eureka
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: eureka
        image: registry.cn-hangzhou.aliyuncs.com/lianghaijun/eureka:springcloud
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8761
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka-0.eureka:8761/eureka,http://eureka-1.eureka:8761/eureka

---

apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: default
  labels:
    k8s-app: eureka
    kubernetes.io/cluster-service: "true"
spec:
  type: ClusterIP
  #clusterIP: None
  selector:
    k8s-app: eureka
  ports:
  - name: eureka
    port: 8761
    targetPort: 8761
  - name: http
    port: 80
    targetPort: 8761
