apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: default
  labels:
    k8s-app: eureka
    kubernetes.io/cluster-service: "true"
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    k8s-app: eureka
  ports:
  - name: http
    port: 8761
    targetPort: 8761

---
      
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
  namespace: default
spec:
  replicas: 2
  serviceName: eureka
  selector:
    matchLabels:
      k8s-app: eureka
  template:
    metadata:
      labels:
        k8s-app: eureka
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: eureka
        image: hub.c.163.com/springcloud/eureka:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8761
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka-0.eureka:8761/eureka,http://eureka-1.eureka:8761/eureka
