apiVersion: apps/v1   # 1.9.0 之前的版本使用 apps/v1beta2，可通过命令 kubectl api-versions 查看
kind: Deployment    #指定创建资源的角色/类型
metadata:    #资源的元数据/属性
  name: nginx      #资源的名字，在同一个namespace中必须唯一
spec:
  replicas: 1    #副本数量2
  selector:
    matchLabels:
      app: nginx
  template:      #这里Pod的定义
    metadata:
      labels:    #Pod的label
        app: nginx
        env: prod
    spec:        # 指定该资源的内容 
      containers: 
      - name: nginx      #容器的名字 
        image: registry-vpc.cn-hangzhou.aliyuncs.com/lianghaijun/nginx-with-tools:latest  #容器的镜像地址   
        volumeMounts:
        - name: etc-nginx
          mountPath: /etc/nginx/nginx.conf
        ports: 
        - containerPort: 80  #容器对外的端口
        resources:
          limits:
            aliyun/eni: 0
      volumes:
      - name: etc-nginx
        hostPath:
          path: /etc/nginx/nginx.conf


---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 8088
    nodePort: 80


